version: '3'

services:
    app:
        container_name: app
        build:
          context: .
          dockerfile: Dockerfile.app
        ports:
        - 5000:5000
        networks:
            - backend
        depends_on:
            - search
        environment:
            - ENVIRONMENT_DEBUG = True

    search:
        container_name: es
        build:
            context: .
            dockerfile: Dockerfile.search
        ports:
            - "9200:9200"
            - "9300:9300"
        networks:
            - backend
        #volumes:
        #    - dbtest:/docker-entrypoint-initdb.d
networks:
    backend:
#volumes:
#    dbtest: