FROM node:10.18.0-alpine3.9 as node
COPY /flask-app /app
WORKDIR /app

RUN npm install && npm run build

FROM nginx:stable-alpine
COPY proxy/nginx.conf /etc/nginx/nginx.conf
COPY --from=node /app/templates /app
COPY --from=node /app/static/build /app/static/build
COPY --from=node /app/static/icons /app/static/icons
COPY --from=node /app/static/styles /app/static/styles

